name: Test Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Task
        run: echo "Hello World"

      - name: check date
        run: date
        

      
